title: Hacker-Blog
description: "Just another blog about IT"
author:
  name: "Maxim Bukvich"
  email: "maxim@bukvich.com"
  url: "https://maxim.bukvich.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Maxim Bukvich"
year : "2021"
